In [1]:
from find_and_judge import *

In [6]:
arr = [
    np.array(
    [[1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0]]),
    np.array(
    [[1.0, 1.0, 2.0],
    [1.0, 1.0, 2.0],
    [1.0, 1.0, 2.0]]),
    np.array(
    [[1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0],
    [2.0, 2.0, 2.0]])
]

found = [
    [np.array([1, 1]),],
    [np.array([1, 1]),],
    [np.array([1, 2]),],
]

print(frac_part(arr[0], found[0][0], 1))
print(get_float_result(arr, found, 1))
print(get_float_result(arr, found, 2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0.5 0.5]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 2.]
 [1. 1. 2.]
 [1. 1. 2.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [0. 0. 0.]]
[[array([1.5, 1.5])], [array([1.5 , 1.75])], [array([1.16666667, 2.5       ])]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 0.]
 [0. 1. 1. 2. 0.]
 [0. 1. 1. 2. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 2. 2. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[array([1.5, 1.5])], [array([1.5 , 1.75])], [array([0.75, 2.5 ])]]
